pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your/repository.git'
            }
        }
        stage('Test') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest'
            }
        }
        stage('Code Quality') {
            steps {
                sh 'flake8 .'
            }
        }
        stage('Build') {
            steps {
                echo 'Build step...'
            }
        }
    }
}
